[package]
name = "investigation-rocket"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]

[dependencies]
serde_json = "0.9"
rocket = "0.2.0"
rocket_codegen = "0.2.0"
rocket_contrib = "0.2.0"
lazy_static = "0.2"

[dependencies.a4-proto]
git = "https://github.com/pgblrsgw/a4-proto"
rev = "54fc1f59e5f9ca7bedb8878f90a401cbac5f8045"

[dev-dependencies]
rocket = { version = "0.2.0", features = ["testing"] }